# escape=`
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8

# Executed as cmd /S /C echo hello
SHELL ["cmd", "/s", "/c"]

# COPY JavaSetup8u241.exe C:\jreinstaller.exe
# RUN powershell -Command `
#     Start-Process -filepath C:\jreinstaller.exe -passthru -wait `
#         -argumentlist "/s,INSTALLDIR=c:\Java\jre1.8.0_241" ; `
#     del -Force C:\jreinstaller.exe

RUN powershell -Command `
        wget 'http://javadl.oracle.com/webapps/download/AutoDL?BundleId=210185' `
            -Outfile 'C:\jreinstaller.exe' ; `
        Start-Process -filepath 'C:\jreinstaller.exe' -passthru -wait `
            -argumentlist '/s INSTALLDIR=C:\Java\jre1.8.0_241' ; `
        del -Force C:\jreinstaller.exe

ENV JAVA_HOME c:\Java\jre1.8.0_241

RUN setx PATH "%PATH%;%JAVA_HOME%\bin" /M

CMD [ "java.exe", "-version" ]

#  docker build --rm -f Dockerfile_WindowsJava -t windows/sdk48/java:latest .
