# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2019

# COPY JavaSetup8u241.exe C:\jreinstaller.exe
# RUN powershell -Command `
#     Start-Process -filepath C:\jreinstaller.exe -passthru -wait `
#         -argumentlist "/s,INSTALLDIR=c:\Java\jre1.8.0_241" ; `
#     del -Force C:\jreinstaller.exe

RUN powershell -Command `
    wget 'https://javadl.oracle.com/webapps/download/AutoDL?BundleId=241505_1f5b5a70bf22433b84d0e960903adac8' `
        -Outfile 'C:\jreinstaller.exe' ; `
    Start-Process -filepath C:\jreinstaller.exe -passthru -wait `
        -argumentlist "/s,INSTALLDIR=c:\Java\jre1.8.0_241" ; `
    del -Force C:\jreinstaller.exe
ENV JAVA_HOME c:\Java\jre1.8.0_241

# RUN setx PATH %PATH%;%JAVA_HOME%\bin /M

CMD [ "java.exe", "-version" ]

#  docker build --rm -f Dockerfile_WindowsJava -t windows/java:latest .
